# Generated by Django 3.1.7 on 2021-03-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
            ],
        ),
    ]
