# Generated by Django 3.1.7 on 2021-03-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesdisplay', '0003_store_nearby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Delivery',
                'managed': False,
            },
        ),
    ]
