# Generated by Django 3.1.7 on 2021-03-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storesdisplay', '0004_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Stores',
        ),
    ]
