# Generated by Django 3.1.7 on 2021-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesdisplay', '0005_auto_20210318_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('driver_first', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_last', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_email', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('card_company', models.TextField(blank=True, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('card_expiration', models.DateField(blank=True, null=True)),
                ('card_ccv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Payment Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shopping Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('user_password', models.TextField(blank=True, null=True)),
                ('user_first', models.TextField(blank=True, null=True)),
                ('user_last', models.TextField(blank=True, null=True)),
                ('permission', models.IntegerField(blank=True, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=25, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'managed': False},
        ),
    ]
