# Generated by Django 3.1.7 on 2021-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesdisplay', '0002_auto_20210316_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='nearby',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
